kpatch: create install directory before touching reliability files
Signed-off-by: Qian Lu <luqia@amazon.com>

diff --git a/kpatch/kpatch b/kpatch/kpatch
--- a/kpatch/kpatch
+++ b/kpatch/kpatch
@@ -461,6 +461,7 @@ check_start_all() {
 			return
 		elif [[ ! -e "$INSTALLDIR/$FILE_PREFIX$i" ]]; then
 			echo "touch file $INSTALLDIR/$FILE_PREFIX$i"
+			mkdir -p "$INSTALLDIR" || die "failed to create install directory"
 			touch "$INSTALLDIR/$FILE_PREFIX$i"
 			sync
 			break
